### ISSUE TITLE
Invalid certificate for www.varlink.org

### ISSUE THREAD

**Issue by Jaakkonen** [varlink/varlink.github.io#17]
When going to [https://www.varlink.org](https://www.varlink.org)  for first time you encounter a certificate issue as with that host the server responds with `www.github.com` CN cert. The server then redirects you to a correctly signed server `varlink.org`  (Let's encrypt cert with `varlink.org` cert)

See [Custom domain for GitHub project pages](https://stackoverflow.com/questions/9082499/custom-domain-for-github-project-pages) on Stackoverflow for solution. This seems to be caused by `Enforce HTTPS` not being on the Github Pages configuration

**Comment by haraldh** [comment]
Works now...

For firefox, I had to accept the security issue once and in the History `forget about the site completely` to remove the old redirection. Now it wo
