### ISSUE TITLE
Suggested additions (ExpectedMore + PermissionDenied errors)

### ISSUE THREAD

**Issue by poettering** [varlink/varlink.github.io#22]
In systemd we started to make more use of varlink then before. There are two extensions of the spec i'd like to see, and I was wondering if they might be considered.

Specifically, an standard error "org.varlink.service.ExpectedMore" which method calls could return that expect to be called with "more" but find out they are not. i.e. subscription or listing method calls really make no sense to be called without "more", and it would be nice if there was a common error defined for cases like this.

I'd also like to see a standard error "org.varlink.service.PermissionDenied" which servers can return when they don#t want a client to access. 

Neither of these errors should have any parameters. In the ExpectedMore cases because there simply is no further context to return. In the PermissionDenied case because details about permission errors should probably not be leaked to unprivileged clients (and instead be logged to a suitable place).

(I am not sure if the web site is the right project to file this against, but given that the specs are maintained here it made the most sense to me)

**Comment by haraldh** [comment]
sounds reasonable

**Comment by haraldh** [comment]
https://github.com/varlink/libvarlink/blob/master/lib/org.varlink.service.varlink

**Comment by poettering** [comment]
Yeah, that one!

**Comment by poettering** [comment]
→ #25
