### ISSUE TITLE
GraphQL...?

### ISSUE THREAD

**Issue by aledomu** [varlink/varlink.github.io#3]
Just to be clear, I'm not sure I really grasp what's going on, but a question popped up in my head while reading this.

Does using GraphQL apply here? From what I see in [its website](http://graphql.org/learn/) it works in both the API access and the definition of the API.

My concerns are about not reinventing the wheel and, seeing that this has lots of potential for programmatic remote system administration, using GraphQL or building on top of it (if it meets the demands) seems like a reasonable option that might lower the entry-barrier for (web) developers since they can reuse another skill which is seeing adoption at a moderate pace. Plus it will allow to query only the required information and not just dumping everything under a tree.

Whether this is going to be considered or it is a totally misled idea, don't hesitate to comment.

**Comment by kaysievers** [comment]
Varlink aims to be the simplest possible and still useful protocol:
  https://varlink.org/Ideals

GraphQL seems nice and useful, but is totally out of scope. Varlink is more an alternative to UNIX command line options and STDOUT parsing, than it is to SQL, Grpc, D-Bus, ...
