### ISSUE TITLE
Method overloading allowed?

### ISSUE THREAD

**Issue by tvannahl** [varlink/varlink.github.io#4]
Is overloading basically allowed?

Consider the following example:
```nim
 # Jump to the calculated point in space
method Jump(configuration: DriveConfiguration) -> ()

# Jump to a point relative from the center of the milky way
method Jump(x: int, y: int, z: int) -> ()
```

Under languages like Java or C there would be no problem to allow overloading, but other languages such as Python or Rust this would require a pre defined handling of such cases.

**Comment by haraldh** [comment]
no, it's not allowed

**Comment by tvannahl** [comment]
Closing, since its documented by referenced commit.
