### ISSUE TITLE
Document client & server communication protocol time outs

### ISSUE THREAD

**Issue by tasleson** [varlink/varlink.github.io#5]
From looking at the documentation and reading some of the rust code it appears that other than specifying an accept timeout for the service, that the protocol itself has no timeouts?  I think it would be good to add some statement(s) to the effect that this is the accepted protocol standard or if this is an API to API implemented stated value etc.

**Comment by tasleson** [comment]
> What exactly do you have in mind?

When implementing a service it's good to know what time constraints may exist in servicing client requests, what the expectation is.

I think it would be good to add this information to the specification documentation.  That in general there is no socket timeout, that individual service APIs can define them as needed and should be clearly stated in their API documentation.

**Comment by kaysievers** [comment]
Hmm, that really sounds like a misunderstanding. Varlink is the simplest UNIX stuff possible, varlink does not impose any limits, timeouts, quota, user accounting to its peers. It is the opposite of D-Bus regarding that, there is no central component, no multiplexing, no connection sharing, hence there is no need to define any of that. It's just a streaming socket for every single connection, there isn't even a packet header for channels or something, it's all plain operating system primitives. It's not different from the web, it could carry gigabytes, taking days to transfer if both peers support that. :)
