### ISSUE TITLE
How to handle versioning of interface

### ISSUE THREAD

**Issue by tasleson** [varlink/varlink.github.io#6]
When an interface gets added to over time, what is the expected way to maintain backwards compatibility?  At the moment the only thing I can think of is adding a version field to the interface (eg. `org.foo.bar1`, `org.foo.bar2`)  and creating a new interface specification each time a change is made.  However, it would be nice if for example you could add a field to a type without requiring an entire new interface.  What are the suggested ways of handling this?

**Comment by kaysievers** [comment]
Adding new things to an interface should not be a problem, JSON makes is rather easy to add stuff and stay backwards compatible. Clients, if they want to, can figure out exactly what a server supports by looking at the interface description.

In general, if things which are commonly available/used, are changed in incompatible ways, they should get a new identifier (interface or method name) and not just break the interfaces for their users.

There is no explicit version in varlink, interfaces can add them if they find them useful, but there is no need to put that in the protocol. In the end it's just an identifier, if we bump a number, add *_EX to the end, or get an entirely new name, it's all the same result.

Even for C shared libraries the "major" version is part of the SONAME, so the identifier changes if the major version is bumped.
