### ISSUE TITLE
Document more of the back story to varlink design goals

### ISSUE THREAD

**Issue by tasleson** [varlink/varlink.github.io#7]
When reading https://lwn.net/Articles/742675/ it raises some points like, dbus cannot be used before FS are mounted, thus one of the reasons for varlink.  I would like to know why this limitation exists, as I remember there was kdbus which provided dbus support in kernel.  It makes sense that a dbus service is unable to reference configuration files for permissions etc.  which reside on the FS, but I'm not sure how the kernel implementation handled this.

Some background on varlinks benefits with regards to dbus limitation would be good to document.

**Comment by kaysievers** [comment]
Varlink has no relation to D-Bus. It might solve the same problem in some cases, like any IPC meachnism, but it's really not meant to replace it. Varlink is more like "A simple REST, without HTTP, and with added type-safety/introspection" than it relates to D-Bus.

I don't really think the varlink docs should explain well-known limitations in other IPC mechanisms, if there is no clear intention to replace it. That's too much finger-pointing and more a topic of a balanced article than varlink's own documentation. Varlink should actually document what it can do, not what others are can't. :)
